<a href="https://colab.research.google.com/github/JustARandomNJ/AIMLProjs/blob/main/HPP/Housing_Price_Predictor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [69]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [70]:
df = pd.read_csv("Housing.csv")

train, test = train_test_split(df, test_size = 0.2, random_state = 42)

In [71]:
train.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,7525000,6000,3,2,4,yes,no,no,no,yes,1,no,furnished
93,6300000,7200,3,2,1,yes,no,yes,no,yes,3,no,semi-furnished
335,3920000,3816,2,1,1,yes,no,yes,no,yes,2,no,furnished
412,3430000,2610,3,1,2,yes,no,yes,no,no,0,yes,unfurnished
471,3010000,3750,3,1,2,yes,no,no,no,no,0,no,unfurnished

In [72]:
train["mainroad"] = train["mainroad"].map({"no": 0, "yes": 1})
train["guestroom"] = train["guestroom"].map({"no": 0, "yes": 1})
train["basement"] = train["basement"].map({"no": 0, "yes": 1})
train["hotwaterheating"] = train["hotwaterheating"].map({"no": 0, "yes": 1})
train["airconditioning"] = train["airconditioning"].map({"no": 0, "yes": 1})
train["prefarea"] = train["prefarea"].map({"no": 0, "yes": 1})
train["furnishingstatus"] = train["furnishingstatus"].map({"unfurnished": 0, "semi-furnished": 1, "furnished": 2})
train.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
46,7525000,6000,3,2,4,1,0,0,0,1,1,0,2
93,6300000,7200,3,2,1,1,0,1,0,1,3,0,1
335,3920000,3816,2,1,1,1,0,1,0,1,2,0,2
412,3430000,2610,3,1,2,1,0,1,0,0,0,1,0
471,3010000,3750,3,1,2,1,0,0,0,0,0,0,0

In [73]:
test["mainroad"] = test["mainroad"].map({"no": 0, "yes": 1})
test["guestroom"] = test["guestroom"].map({"no": 0, "yes": 1})
test["basement"] = test["basement"].map({"no": 0, "yes": 1})
test["hotwaterheating"] = test["hotwaterheating"].map({"no": 0, "yes": 1})
test["airconditioning"] = test["airconditioning"].map({"no": 0, "yes": 1})
test["prefarea"] = test["prefarea"].map({"no": 0, "yes": 1})
test["furnishingstatus"] = test["furnishingstatus"].map({"unfurnished": 0, "semi-furnished": 1, "furnished": 2})

In [74]:
X_train = train.drop("price", axis = 1)
y_train = train["price"]

X_test = test.drop("price", axis = 1)
y_test = test["price"]

In [75]:
model = LinearRegression()
model.fit(X_train, y_train)

LinearRegression()

In [76]:
y_pred = model.predict(X_test)

In [78]:
mae = mean_absolute_error(y_test, y_pred)
rmse = np.sqrt(mean_squared_error(y_test, y_pred))
r2 = r2_score(y_test, y_pred)

In [79]:
print("MAE:", mae)
print("RMSE:", rmse)
print("R²:", r2)

MAE: 979679.6912959901
RMSE: 1331071.4167895108
R²: 0.6494754192267803